# V1: Edgeworth 2×2 - Analytic equilibrium verification
# Expected: ‖p_computed - p_analytic‖ < 1e-8

simulation:
  name: "Edgeworth_2x2_Box"
  description: "Two agents, two goods, analytic solution verification"
  n_agents: 2
  n_goods: 2
  grid_width: 5
  grid_height: 5
  marketplace_width: 2
  marketplace_height: 2
  movement_cost: 0.0  # No spatial frictions for pure theory test
  max_rounds: 10
  random_seed: 42
  
validation:
  type: "analytic_comparison"
  analytic_prices: [1.0, 1.5]  # Expected equilibrium prices
  tolerance: 1e-8